# Generated by Django 3.0.7 on 2020-06-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20200627_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
