# Generated by Django 3.0.7 on 2020-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20200628_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
    ]
